import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react'

const LanguageContext = createContext(null)
const LANGUAGE_KEY = 'shopeasy_language'

const translations = {
  en: {
    nav: {
      brand: 'ShopEasy Food',
      shop: 'Menu',
      cart: 'Cart',
      orders: 'Orders',
      admin: 'Admin',
      signIn: 'Sign in',
      signOut: 'Sign out',
      greeting: 'Hi {name}',
      switchToArabic: 'AR',
      switchToEnglish: 'EN',
    },
    home: {
      heroEyebrow: 'Chef picks',
      heroTitle: 'Fresh meals, fast delivery.',
      heroCopy:
        'Browse the full menu, customize your cart, and track every order from prep to door.',
      heroBrowse: 'Browse menu',
      heroCart: 'View cart',
      metricOneValue: '15-25 min',
      metricOneLabel: 'Delivery window',
      metricTwoValue: 'Live tracking',
      metricTwoLabel: 'Order status updates',
      metricThreeValue: 'COD & online',
      metricThreeLabel: 'Flexible payment',
      highlightsTitle: 'Category highlights',
      highlightsLoading: 'Loading',
      catalogEyebrow: 'Menu',
      catalogTitle: 'Explore the menu',
      catalogMeta: '{count} items',
      itemsLabel: '{count} items',
      loadErrorTitle: 'Could not load menu',
      emptyTitle: 'No menu items yet',
      emptyMessage: 'Try adjusting your filters or check back soon.',
    },
    filters: {
      search: 'Search',
      searchPlaceholder: 'Search meals',
      category: 'Category',
      allCategories: 'All categories',
      minPrice: 'Min price',
      maxPrice: 'Max price',
      sort: 'Sort',
      sortDefault: 'Default',
      sortLow: 'Price: low to high',
      sortHigh: 'Price: high to low',
      sortRecent: 'Recently updated',
      sortOldest: 'Oldest update',
      reset: 'Reset',
    },
    product: {
      inStock: 'Available',
      outOfStock: 'Unavailable',
      addToCart: 'Add to cart',
      noImage: 'No image',
    },
    productDetail: {
      label: 'Menu item',
      goToCart: 'Go to cart',
      outOfStock: 'Unavailable',
      inventory: 'Inventory {count}',
      sku: 'SKU {id}',
      reviewsEyebrow: 'Reviews',
      reviewsTitle: 'What diners say',
      reviewsCount: '{count} reviews',
      reviewName: 'Name',
      reviewText: 'Review',
      postReview: 'Post review',
      posting: 'Posting...',
      noReviewsTitle: 'No reviews yet',
      noReviewsMessage: 'Be the first to share your thoughts.',
      loading: 'Loading item...',
      unavailableTitle: 'Item unavailable',
      backToMenu: 'Back to menu',
      incTax: 'inc tax',
    },
    cart: {
      title: 'Your selections',
      eyebrow: 'Cart',
      itemsLabel: '{count} items',
      emptyTitle: 'Your cart is empty',
      emptyMessage: 'Browse the menu and add your first dish.',
      startShopping: 'Start ordering',
      each: 'each',
      itemTotal: 'Item total',
      subtotal: 'Subtotal',
      taxIncluded: 'Tax is already included in the total.',
      paymentMethod: 'Payment method',
      paymentCod: 'Cash on delivery',
      paymentOnline: 'Online payment',
      paymentHint: 'Select how you want to pay at checkout.',
      placeOrder: 'Place order',
      placingOrder: 'Placing order...',
      signInPrompt: 'Sign in to place your order.',
      signIn: 'Sign in',
      loading: 'Loading cart...',
    },
    orders: {
      eyebrow: 'Orders',
      title: 'Order history',
      loading: 'Loading orders...',
      signInTitle: 'Sign in to view your orders',
      signInMessage: 'Your order history is linked to your account.',
      emptyTitle: 'No orders yet',
      emptyMessage: 'Place your first order from the cart.',
      goToCart: 'Go to cart',
      loadErrorTitle: 'Could not load orders',
      total: 'Total',
      paymentStatus: 'Payment status',
      paymentMethod: 'Payment method',
      orderStatus: 'Order status',
      tracking: 'Tracking',
      orderNumber: 'Order #{id}',
      countLabel: '{count} orders',
    },
    auth: {
      eyebrow: 'Account',
      title: 'Welcome back',
      subtitle: 'Secure JWT sign in',
      signIn: 'Sign in',
      signInCopy: 'Use your username and password.',
      createAccount: 'Create account',
      createCopy: 'Join to track orders and save profiles.',
      username: 'Username',
      password: 'Password',
      confirmPassword: 'Confirm password',
      email: 'Email',
      firstName: 'First name',
      lastName: 'Last name',
      signingIn: 'Signing in...',
      creating: 'Creating...',
      accountCreated: 'Account created. Sign in to continue.',
      passwordMismatch: 'Passwords do not match.',
      alreadyTitle: 'You are already signed in',
      alreadyMessage:
        'Visit your profile to manage your account or keep shopping.',
      goToProfile: 'Go to profile',
    },
    profile: {
      eyebrow: 'Profile',
      title: 'Account overview',
      subtitle: 'Customer details',
      userCard: 'User',
      customerCard: 'Customer',
      membership: 'Membership',
      birthDate: 'Birth date',
      phone: 'Phone',
      updateTitle: 'Update profile',
      save: 'Save changes',
      saving: 'Saving...',
      updated: 'Profile updated successfully.',
      signInTitle: 'Sign in to view your profile',
      signInMessage:
        'Your customer profile and membership details live here.',
      signIn: 'Sign in',
      notSet: 'Not set',
    },
    admin: {
      eyebrow: 'Admin',
      pageTitle: 'Operations dashboard',
      subtitle: 'Manage menu items and monitor orders in one place.',
      productsTitle: 'Menu management',
      categoriesTitle: 'Category management',
      ordersTitle: 'Order monitoring',
      searchPlaceholder: 'Search menu items',
      searchCollectionsPlaceholder: 'Search categories',
      searchOrdersPlaceholder: 'Search orders',
      addProduct: 'Add product',
      editProduct: 'Edit product',
      addCategory: 'Add category',
      editCategory: 'Edit category',
      delete: 'Delete',
      save: 'Save',
      cancel: 'Cancel',
      update: 'Update',
      updating: 'Updating...',
      inventory: 'Inventory',
      fieldTitle: 'Title',
      titleAr: 'Title (Arabic)',
      description: 'Description',
      descriptionAr: 'Description (Arabic)',
      category: 'Category',
      slug: 'Slug',
      images: 'Images',
      addImage: 'Add image',
      chooseFile: 'Choose image',
      replaceImage: 'Replace image',
      removeImage: 'Remove image',
      uploadImage: 'Upload image',
      currentImages: 'Current images',
      price: 'Price',
      status: 'Status',
      payment: 'Payment',
      method: 'Method',
      noCategory: 'No category selected',
      noOrders: 'No orders to monitor yet.',
      noProducts: 'No menu items found.',
      noCategories: 'No categories found.',
      noDescription: 'No description provided.',
      requireLogin: 'Sign in to access the admin dashboard.',
      requireStaff: 'You do not have permission to access the admin dashboard.',
      productSaved: 'Product saved successfully.',
      productDeleted: 'Product deleted successfully.',
      categorySaved: 'Category saved successfully.',
      categoryDeleted: 'Category deleted successfully.',
    },
    footer: {
      aboutTitle: 'ShopEasy Food',
      aboutCopy:
        'Chef-made meals, transparent pricing, and tracking that keeps you in the loop.',
      explore: 'Explore',
      support: 'Support',
      catalog: 'Menu',
      supportEmail: 'support@shopeasy.local',
      supportHours: 'Everyday 9:00 - 18:00',
      returns: 'Fast support for every order',
      bottomLeft: 'All prices include tax.',
      bottomRight: 'ShopEasy Food UI for Django REST.',
    },
    common: {
      noImage: 'No image',
      loading: 'Loading...',
      reset: 'Reset',
    },
    notFound: {
      title: 'Page not found',
      message: 'The page you are looking for has moved or does not exist.',
      action: 'Back to menu',
    },
  },
  ar: {
    nav: {
      brand: 'شوب إيزي فود',
      shop: 'المنيو',
      cart: 'السلة',
      orders: 'الطلبات',
      admin: 'لوحة الادارة',
      signIn: 'تسجيل الدخول',
      signOut: 'تسجيل الخروج',
      greeting: 'اهلا {name}',
      switchToArabic: 'ع',
      switchToEnglish: 'EN',
    },
    home: {
      heroEyebrow: 'اختيارات الشيف',
      heroTitle: 'وجبات طازجة وتوصيل سريع.',
      heroCopy:
        'تصفح المنيو بالكامل، خصص سلتك، وتابع الطلب خطوة بخطوة حتى بابك.',
      heroBrowse: 'تصفح المنيو',
      heroCart: 'عرض السلة',
      metricOneValue: '15-25 دقيقة',
      metricOneLabel: 'نافذة التوصيل',
      metricTwoValue: 'تتبع حي',
      metricTwoLabel: 'تحديثات حالة الطلب',
      metricThreeValue: 'كاش او اونلاين',
      metricThreeLabel: 'طرق دفع مرنة',
      highlightsTitle: 'ابرز الاقسام',
      highlightsLoading: 'جاري التحميل',
      catalogEyebrow: 'المنيو',
      catalogTitle: 'استكشف المنيو',
      catalogMeta: '{count} عنصر',
      itemsLabel: '{count} عنصر',
      loadErrorTitle: 'تعذر تحميل المنيو',
      emptyTitle: 'لا يوجد عناصر بعد',
      emptyMessage: 'جرب تغيير الفلاتر او عد لاحقا.',
    },
    filters: {
      search: 'بحث',
      searchPlaceholder: 'ابحث عن وجبة',
      category: 'القسم',
      allCategories: 'كل الاقسام',
      minPrice: 'اقل سعر',
      maxPrice: 'اعلى سعر',
      sort: 'ترتيب',
      sortDefault: 'افتراضي',
      sortLow: 'السعر: من الاقل للاعلى',
      sortHigh: 'السعر: من الاعلى للاقل',
      sortRecent: 'احدث تحديث',
      sortOldest: 'اقدم تحديث',
      reset: 'اعادة',
    },
    product: {
      inStock: 'متاح',
      outOfStock: 'غير متاح',
      addToCart: 'اضافة للسلة',
      noImage: 'لا يوجد صورة',
    },
    productDetail: {
      label: 'عنصر منيو',
      goToCart: 'اذهب للسلة',
      outOfStock: 'غير متاح',
      inventory: 'المخزون {count}',
      sku: 'الرقم {id}',
      reviewsEyebrow: 'التقييمات',
      reviewsTitle: 'اراء العملاء',
      reviewsCount: '{count} تقييم',
      reviewName: 'الاسم',
      reviewText: 'التقييم',
      postReview: 'ارسال التقييم',
      posting: 'جاري الارسال...',
      noReviewsTitle: 'لا توجد تقييمات بعد',
      noReviewsMessage: 'كن اول من يشارك رايه.',
      loading: 'جاري تحميل العنصر...',
      unavailableTitle: 'العنصر غير متاح',
      backToMenu: 'العودة للمنيو',
      incTax: 'شامل الضريبة',
    },
    cart: {
      title: 'اختياراتك',
      eyebrow: 'السلة',
      itemsLabel: '{count} عنصر',
      emptyTitle: 'سلتك فارغة',
      emptyMessage: 'تصفح المنيو واضف اول وجبة.',
      startShopping: 'ابدأ الطلب',
      each: 'للوحدة',
      itemTotal: 'اجمالي العنصر',
      subtotal: 'المجموع',
      taxIncluded: 'الضريبة مشمولة في الاجمالي.',
      paymentMethod: 'طريقة الدفع',
      paymentCod: 'كاش عند الاستلام',
      paymentOnline: 'دفع اونلاين',
      paymentHint: 'اختر طريقة الدفع المناسبة.',
      placeOrder: 'تنفيذ الطلب',
      placingOrder: 'جاري تنفيذ الطلب...',
      signInPrompt: 'سجل الدخول لاكمال الطلب.',
      signIn: 'تسجيل الدخول',
      loading: 'جاري تحميل السلة...',
    },
    orders: {
      eyebrow: 'الطلبات',
      title: 'سجل الطلبات',
      loading: 'جاري تحميل الطلبات...',
      signInTitle: 'سجل الدخول لعرض طلباتك',
      signInMessage: 'سجل طلباتك مرتبط بحسابك.',
      emptyTitle: 'لا توجد طلبات بعد',
      emptyMessage: 'قم بعمل اول طلب من السلة.',
      goToCart: 'اذهب للسلة',
      loadErrorTitle: 'تعذر تحميل الطلبات',
      total: 'الاجمالي',
      paymentStatus: 'حالة الدفع',
      paymentMethod: 'طريقة الدفع',
      orderStatus: 'حالة الطلب',
      tracking: 'التتبع',
      orderNumber: 'طلب رقم {id}',
      countLabel: '{count} طلب',
    },
    auth: {
      eyebrow: 'الحساب',
      title: 'اهلا بعودتك',
      subtitle: 'تسجيل دخول امن',
      signIn: 'تسجيل الدخول',
      signInCopy: 'استخدم اسم المستخدم وكلمة المرور.',
      createAccount: 'انشاء حساب',
      createCopy: 'انضم لتتبع الطلبات وحفظ بياناتك.',
      username: 'اسم المستخدم',
      password: 'كلمة المرور',
      confirmPassword: 'تأكيد كلمة المرور',
      email: 'البريد الالكتروني',
      firstName: 'الاسم الاول',
      lastName: 'اسم العائلة',
      signingIn: 'جاري تسجيل الدخول...',
      creating: 'جاري الانشاء...',
      accountCreated: 'تم انشاء الحساب. سجل الدخول للمتابعة.',
      passwordMismatch: 'كلمتا المرور غير متطابقتين.',
      alreadyTitle: 'انت مسجل الدخول بالفعل',
      alreadyMessage: 'يمكنك ادارة حسابك من الملف الشخصي.',
      goToProfile: 'الملف الشخصي',
    },
    profile: {
      eyebrow: 'الملف الشخصي',
      title: 'نظرة عامة',
      subtitle: 'بيانات العميل',
      userCard: 'المستخدم',
      customerCard: 'العميل',
      membership: 'العضوية',
      birthDate: 'تاريخ الميلاد',
      phone: 'الهاتف',
      updateTitle: 'تحديث البيانات',
      save: 'حفظ',
      saving: 'جاري الحفظ...',
      updated: 'تم تحديث البيانات بنجاح.',
      signInTitle: 'سجل الدخول لعرض ملفك',
      signInMessage: 'بيانات العميل والعضوية تظهر هنا.',
      signIn: 'تسجيل الدخول',
      notSet: 'غير محدد',
    },
    admin: {
      eyebrow: 'الادارة',
      pageTitle: 'لوحة التشغيل',
      subtitle: 'ادارة عناصر المنيو ومتابعة الطلبات.',
      productsTitle: 'ادارة المنيو',
      categoriesTitle: 'ادارة الاقسام',
      ordersTitle: 'متابعة الطلبات',
      searchPlaceholder: 'ابحث عن عنصر في المنيو',
      searchCollectionsPlaceholder: 'ابحث عن قسم',
      searchOrdersPlaceholder: 'ابحث عن طلب',
      addProduct: 'اضافة منتج',
      editProduct: 'تعديل منتج',
      addCategory: 'اضافة قسم',
      editCategory: 'تعديل قسم',
      delete: 'حذف',
      save: 'حفظ',
      cancel: 'الغاء',
      update: 'تحديث',
      updating: 'جاري التحديث...',
      inventory: 'المخزون',
      fieldTitle: 'العنوان',
      titleAr: 'العنوان بالعربية',
      description: 'الوصف',
      descriptionAr: 'الوصف بالعربية',
      category: 'القسم',
      slug: 'الرابط',
      images: 'الصور',
      addImage: 'اضافة صورة',
      chooseFile: 'اختر صورة',
      replaceImage: 'استبدال صورة',
      removeImage: 'حذف الصورة',
      uploadImage: 'رفع صورة',
      currentImages: 'الصور الحالية',
      price: 'السعر',
      status: 'الحالة',
      payment: 'الدفع',
      method: 'الطريقة',
      noCategory: 'لا يوجد قسم محدد',
      noOrders: 'لا توجد طلبات للمتابعة حاليا.',
      noProducts: 'لا توجد عناصر مطابقة.',
      noCategories: 'لا توجد اقسام.',
      noDescription: 'لا يوجد وصف.',
      requireLogin: 'سجل الدخول للوصول للوحة الادارة.',
      requireStaff: 'ليس لديك صلاحية الوصول للوحة الادارة.',
      productSaved: 'تم حفظ المنتج بنجاح.',
      productDeleted: 'تم حذف المنتج بنجاح.',
      categorySaved: 'تم حفظ القسم بنجاح.',
      categoryDeleted: 'تم حذف القسم بنجاح.',
    },
    footer: {
      aboutTitle: 'شوب إيزي فود',
      aboutCopy: 'وجبات طازجة، اسعار واضحة، وتتبع لحظي لكل طلب.',
      explore: 'استكشف',
      support: 'الدعم',
      catalog: 'المنيو',
      supportEmail: 'support@shopeasy.local',
      supportHours: 'يوميا 9:00 - 18:00',
      returns: 'دعم سريع لكل طلب',
      bottomLeft: 'الاسعار تشمل الضريبة.',
      bottomRight: 'واجهة شوب إيزي فود مع Django REST.',
    },
    common: {
      noImage: 'لا يوجد صورة',
      loading: 'جاري التحميل...',
      reset: 'اعادة',
    },
    notFound: {
      title: 'الصفحة غير موجودة',
      message: 'قد تكون الصفحة انتقلت او غير موجودة.',
      action: 'العودة للمنيو',
    },
  },
}

const locales = {
  en: 'en-US',
  ar: 'ar-EG',
}

const directions = {
  en: 'ltr',
  ar: 'rtl',
}

const resolvePath = (object, path) =>
  path.split('.').reduce((acc, key) => (acc ? acc[key] : undefined), object)

const loadLanguage = () => {
  try {
    const stored = localStorage.getItem(LANGUAGE_KEY)
    return stored === 'ar' ? 'ar' : 'en'
  } catch {
    return 'en'
  }
}

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(loadLanguage)

  useEffect(() => {
    try {
      localStorage.setItem(LANGUAGE_KEY, language)
    } catch {
      // ignore
    }
    document.documentElement.lang = language
    document.documentElement.dir = directions[language] || 'ltr'
  }, [language])

  const t = useCallback(
    (key, params) => {
      const raw =
        resolvePath(translations[language], key) ||
        resolvePath(translations.en, key) ||
        key
      if (typeof raw !== 'string') return key
      if (!params) return raw
      return raw.replace(/\{(\w+)\}/g, (_, name) =>
        params[name] === undefined ? '' : String(params[name]),
      )
    },
    [language],
  )

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      locale: locales[language] || 'en-US',
      direction: directions[language] || 'ltr',
      t,
      isArabic: language === 'ar',
    }),
    [language, t],
  )

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

export const getLocalizedField = (value, valueAr, language) => {
  if (language === 'ar' && valueAr) return valueAr
  return value || valueAr || ''
}
