# Generated by Django 6.0.1 on 2026-01-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
