# Generated by Django 6.0.1 on 2026-01-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='member_ship',
            new_name='membership',
        ),
    ]
